[workspace]
allow_dirty = true # allow updating repositories with uncommitted changes
pr_branch_prefix = "release-plz-" # PR branch prefix
pr_labels = ["release"] # add the `release` label to the release Pull Request
semver_check = true # disable API breaking changes checks
publish_timeout = "10m" # set a timeout for `cargo publish`
# release_commits = "^feat:" # prepare release only if at least one commit matches a regex
git_tag_name = "v{{ version }}"
